export const DOM_IDS = Object.freeze({
  wrapper: "game-wrapper",
  canvas: "gameCanvas",
  hud: "hud",
  healthBar: "health-bar",
  ammoDisplay: "ammo-display",
  comboDisplay: "combo-display",
  score: "score",
  scoreContainer: "score-container",
  uiLayer: "ui-layer",
  mainMenu: "main-menu",
  gameOverMenu: "game-over-menu",
  finalScore: "final-score",
  highScore: "high-score",
  creditsEarned: "credits-earned",
  totalCredits: "total-credits",
  startButton: "start-btn",
  restartButton: "restart-btn",
  upgradesButton: "upgrades-btn",
  gameOverUpgradesButton: "gameover-upgrades-btn",
  upgradeMenu: "upgrade-menu",
  upgradeBalance: "upgrade-balance",
  upgradeList: "upgrade-list",
  closeUpgradesButton: "close-upgrades-btn",
});
